// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.9.1_eslint-ts-patch@8.55.0-1_typescript@5.3.3_vite@5.0.11_vue-tsc@1.8.27/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.6_nuxt@3.9.1_postcss@8.4.3_vkg2nnum7mjtrzfwo5xslhvkti/node_modules/nuxt-site-config/dist/runtime/nitro/routes/__site-config__/debug').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.25_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.6_nuxt@3.9.1_postcss@8._m44uz7b544a2g26itj577wxzlq/node_modules/nuxt-og-image/dist/runtime/server/routes/__og-image__/font-[name]-[weight].[extension]').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.25_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.6_nuxt@3.9.1_postcss@8._m44uz7b544a2g26itj577wxzlq/node_modules/nuxt-og-image/dist/runtime/server/routes/__og-image__/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.25_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.6_nuxt@3.9.1_postcss@8._m44uz7b544a2g26itj577wxzlq/node_modules/nuxt-og-image/dist/runtime/server/routes/__og-image__/image').default>>>>
    }
  }
}
export {}